# Generated by Django 3.2.14 on 2023-04-30 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecostok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.CharField(help_text='Id da Transação', max_length=12, primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('entrada', models.DecimalField(decimal_places=2, help_text='Recebimento em R$', max_digits=6)),
                ('saida', models.DecimalField(decimal_places=2, help_text='Pagamentos em R$', max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='preco_compra',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='Preco_venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cod', models.ForeignKey(help_text='Código Material que Será Vendido', on_delete=django.db.models.deletion.CASCADE, to='ecostok.material')),
            ],
        ),
    ]
