# Generated by Django 3.2.14 on 2023-04-30 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecostok', '0002_auto_20230429_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coletores',
            fields=[
                ('cpf', models.CharField(help_text='CPF dos Coletores de Material Reciclado', max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do Coletor', max_length=50)),
                ('sobrenome', models.CharField(help_text='Sobrenome do Coletor', max_length=50)),
                ('id_caixa', models.ForeignKey(help_text='Id da Transação', on_delete=django.db.models.deletion.CASCADE, to='ecostok.caixa')),
            ],
        ),
    ]
