# Generated by Django 3.2.14 on 2023-04-30 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecostok', '0003_coletores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coletores',
            old_name='id_caixa',
            new_name='caixa_id',
        ),
    ]
