# Generated by Django 3.2.14 on 2023-04-30 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecostok', '0004_rename_id_caixa_coletores_caixa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coletores',
            old_name='caixa_id',
            new_name='pagamento',
        ),
    ]
