# Generated by Django 3.2.14 on 2023-04-30 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecostok', '0006_auto_20230429_2247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coletores',
            new_name='Coletor',
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso do Material Comprado Kg', max_digits=3)),
                ('prensado', models.DecimalField(decimal_places=2, help_text='Peso do Material Prensado Kg', max_digits=3)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor Pago ao Coletor', max_digits=6)),
                ('coletor', models.ForeignKey(help_text='CPF do Coletor', on_delete=django.db.models.deletion.PROTECT, to='ecostok.coletor')),
                ('material', models.ForeignKey(help_text='Código Material que Será Comprado', on_delete=django.db.models.deletion.PROTECT, to='ecostok.material')),
            ],
        ),
    ]
