# Generated by Django 3.2.14 on 2023-04-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecostok', '0008_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(choices=[('V', 'Vendedor'), ('C', 'Comprador'), ('E', 'Estoquista'), ('G', 'Gestor')], default='V', help_text='Função do Funcionario', max_length=1),
        ),
    ]
