# Generated by Django 3.2.14 on 2023-04-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecostok', '0009_funcionario_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(choices=[('v', 'Vendedor'), ('c', 'Comprador'), ('e', 'Estoquista'), ('g', 'Gestor')], default='v', help_text='Função do Funcionario', max_length=1),
        ),
    ]
