# Generated by Django 3.2.14 on 2023-04-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecostok', '0010_alter_funcionario_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(default='v', help_text='Função do Funcionario', max_length=1),
        ),
    ]
