# Generated by Django 3.2.14 on 2023-04-30 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecostok', '0012_alter_funcionario_funcao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cnpj', models.CharField(help_text='CNPJ do Cliente', max_length=14, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(help_text='Razão Social do Cliente', max_length=50)),
                ('nome_fantasia', models.CharField(help_text='Nome Fantasia do Cliente', max_length=50)),
                ('pagamento', models.ForeignKey(help_text='Id da Transação', on_delete=django.db.models.deletion.PROTECT, to='ecostok.caixa')),
            ],
        ),
    ]
