# Generated by Django 3.2.14 on 2023-05-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecostok', '0014_auto_20230430_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
