# Generated by Django 3.2.14 on 2023-05-07 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecostok', '0015_auto_20230506_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pagamento',
            field=models.ForeignKey(default=1, help_text='Id da Transação', on_delete=django.db.models.deletion.PROTECT, to='ecostok.caixa'),
        ),
        migrations.AlterField(
            model_name='coletor',
            name='pagamento',
            field=models.ForeignKey(default=1, help_text='Id da Transação', on_delete=django.db.models.deletion.PROTECT, to='ecostok.caixa'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='pagamento',
            field=models.ForeignKey(default=1, help_text='Id da Transação', on_delete=django.db.models.deletion.PROTECT, to='ecostok.caixa'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='peso',
            field=models.DecimalField(decimal_places=2, help_text='Peso do Material Comprado Kg', max_digits=6),
        ),
    ]
